=== zhouzilong168/javalearning/src/xml/one.dtd
<!ELEMENT roster (class, student+)>
<!ELEMENT class (monitor, department, specialty)
<!ELEMENT student (name, sex?,classto)>
<!ELEMENT monitor EMPTY>
<!ELEMENT department (#PCDATA)>
<!ELEMENT specialty (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT sex (#PCDATA)>
<!ELEMENT classto EMPTY>
<!ATTLIST class id ID #REQUIRED>
<!ATTLIST monitor ip IDREF #REQUIRED>
<!ATTLIST student id ID #REQUIRED >
<!ATTLIST student type CDATA #IMPLIED>
<!ATTLIST name byname CDATA #IMPLIED>
<!ATTLIST classto idf IDREF #REQUIRED>

=== zhouzilong168/javalearning/out/production/javalearning/xml/one.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE roster SYSTEM "F:\IDEA\javalearning\src\others\xml\one.dtd">
<roster>
    <class id="c101">
        <monitor ip="s101"/>
        <department>信息工程</department>
        <specialty>计算机应用</specialty>
    </class>
    <student id="s101" type="特长生">
        <name>李华</name>
        <sex>男</sex>
        <classto idf="s101"/>
    </student>
    <student id="s102">
        <name byname="西门飘雪">倪冰</name>
        <classto idf="s101"/>
    </student>
</roster>
