=== zhouzilong168/javalearning/out/production/javalearning/xml/ex1.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            elementFormDefault="qualified">
    <!--类型定义 学生元素类型+课程元素类型-->
    <!--学生元素类型-->
    <xsd:complexType name="stuType">
        <xsd:sequence>
            <xsd:element ref="name"/>
            <xsd:element ref="sex"/>
            <xsd:element name="date" type="xsd:date"/>
            <!--一个学生可选多门课，课程设置为不受限-->
            <xsd:element name="course" maxOccurs="unbounded">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element ref="score"/>
                    </xsd:sequence>
                    <xsd:attribute ref="id" use="required"/>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
        <xsd:attribute ref="id" use="required"/>
    </xsd:complexType>

    <!--课程元素类型-->
    <xsd:complexType name="couType">
        <xsd:sequence>
            <xsd:element ref="name"/>
            <xsd:element name="credit" type="xsd:decimal"/>
            <xsd:element name="note" type="xsd:string"/>
        </xsd:sequence>
        <xsd:attribute ref="id" use="required"/>
    </xsd:complexType>

    <!--属性定义-->
    <!--学生和课程可使用相同的id定义-->
    <xsd:attribute name="id" type="xsd:string"/>

    <!--元素的定义 学生+名字+性别+课程+分数-->
    <xsd:element name="student" type="stuType"/>
    <!--名字，学生、课程都有名字，定义在外部，全局引用-->
    <xsd:element name="name" type="xsd:string"/>
    <!--性别，枚举限制-->
    <xsd:element name="sex">
        <xsd:simpleType>
            <xsd:restriction base="xsd:string">
                <xsd:enumeration value="male"/>
                <xsd:enumeration value="female"/>
            </xsd:restriction>
        </xsd:simpleType>
    </xsd:element>
    <!--课程-->
    <xsd:element name="course" type="couType"/>
    <!--分数-->
    <xsd:element name="score">
        <xsd:complexType>
            <xsd:sequence><!--子元素定义必选/可选，通过minOccurs设置-->
                <xsd:element name="normal" type="xsd:decimal" minOccurs="1"/>
                <xsd:element name="retake" type="xsd:decimal" minOccurs="0"/>
                <xsd:element name="rebuild" type="xsd:decimal" minOccurs="0"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <!--全局有名类型school-->
    <xsd:element name="school">
        <xsd:complexType>
            <xsd:sequence>
                <!--学校可有多个学生，数量设置为不受限-->
                <xsd:element ref="student" maxOccurs="unbounded"/>
                <!--学校可开设多门课程，数量设置为不受限-->
                <xsd:element ref="course" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

        <!--
                <?xml version="1.0"?>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                    elementFormDefault="qualified">
        &lt;!&ndash;类型定义 学生元素类型+课程元素类型&ndash;&gt;
        &lt;!&ndash;学生元素类型&ndash;&gt;
        <xsd:complexType name="stuType">
            <xsd:sequence>
                <xsd:element ref="name"/>
                <xsd:element ref="sex"/>
                <xsd:element name="date" type="xsd:date"/>
                &lt;!&ndash;一个学生可选多门课，课程设置为不受限&ndash;&gt;
                <xsd:element ref="course" maxOccurs="unbounded"/>
            </xsd:sequence>
            <xsd:attribute ref="id" use="required"/>
        </xsd:complexType>

        &lt;!&ndash;课程元素类型&ndash;&gt;
        <xsd:complexType name="couType">
            <xsd:sequence>
                <xsd:element ref="name"/>
                <xsd:element name="credit" type="xsd:decimal"/>
                <xsd:element name="note" type="xsd:string"/>
                <xsd:element ref="score"/>
            </xsd:sequence>
            <xsd:attribute ref="id" use="required"/>
        </xsd:complexType>

        &lt;!&ndash;属性定义&ndash;&gt;
        &lt;!&ndash;学生和课程可使用相同的id定义&ndash;&gt;
        <xsd:attribute name="id" type="xsd:string"/>

        &lt;!&ndash;元素的定义 学生+名字+性别+课程+分数&ndash;&gt;
        <xsd:element name="student" type="stuType"/>
        &lt;!&ndash;名字，学生、课程都有名字，定义在外部，全局引用&ndash;&gt;
        <xsd:element name="name" type="xsd:string"/>
        &lt;!&ndash;性别，枚举限制&ndash;&gt;
        <xsd:element name="sex">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="male"/>
                    <xsd:enumeration value="female"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:element>
        &lt;!&ndash;课程&ndash;&gt;
        <xsd:element name="course" type="couType"/>
        &lt;!&ndash;分数&ndash;&gt;
        <xsd:element name="score">
            <xsd:complexType mixed="true">&lt;!&ndash;定义混合类型&ndash;&gt;
                <xsd:attribute name="type" use="required">&lt;!&ndash;限制属性类型，为成绩类型&ndash;&gt;
                    <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                            <xsd:enumeration value="normal"/>&lt;!&ndash;正常考试成绩&ndash;&gt;
                            <xsd:enumeration value="retake"/>&lt;!&ndash;补考成绩&ndash;&gt;
                            <xsd:enumeration value="rebuild"/>&lt;!&ndash;重修成绩&ndash;&gt;
                        </xsd:restriction>
                    </xsd:simpleType>
                </xsd:attribute>
            </xsd:complexType>
        </xsd:element>
        &lt;!&ndash;全局有名类型school&ndash;&gt;
        <xsd:element name="school">
            <xsd:complexType>
                <xsd:sequence>&lt;!&ndash;学校可有多个学生，数量设置为不受限&ndash;&gt;
                    <xsd:element ref="student" maxOccurs="unbounded"/>
                </xsd:sequence>
            </xsd:complexType>
        </xsd:element>
        </xsd:schema>-->

=== zhouzilong168/javalearning/src/xml/ex1.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="ex1_3.xsl"?>
<school xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="ex1.xsd">
    <!--引入同一个文件夹下的xsd文件-->
    <student id="0121710870720"><!--可以定义多个学生-->
        <name>zzz</name><!--学生姓名-->
        <sex>male</sex><!--学生性别（枚举）：male/female-->
        <date>1999-01-06</date><!--出生日期-->
        <course id="1010">
            <!--课程分数，属性type表示成绩性质（枚举）：正常/补考/重修-->
            <score>
                <normal>99.99</normal>
            </score>
        </course><!--一个学生可选修多门课程-->
        <course id="1011">
            <score>
                <normal>56</normal>
                <retake>59</retake>
                <rebuild>60</rebuild>
            </score>
        </course>
    </student>
    <student id="123133213">
        <name>sdf</name>
        <sex>male</sex>
        <date>1999-12-12</date>
        <course id="1011">
            <score>
                <normal>79</normal>
            </score>
        </course>
    </student>
    <student id="0121710870721">
        <name>lfb</name>
        <sex>female</sex>
        <date>1999-11-19</date>
        <course id="1010">
            <score>
                <normal>56</normal>
                <retake>68</retake>
            </score>
        </course>
    </student>
    <!--课程-->
    <course id="1010">
        <name>xml</name>
        <credit>2.0</credit>
        <note>this is a very important class</note>
    </course>
    <course id="1011">
        <name>java</name>
        <credit>3.0</credit>
        <note>java program design</note>
    </course>
</school>

<!--
        <?xml version="1.0" encoding="utf-8"?>
        <?xml-stylesheet type="text/xsl" href="ex1_3.xsl"?>
<school xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="ex1.xsd">
&lt;!&ndash;引入同一个文件夹下的xsd文件&ndash;&gt;
<student id="0121710870720">&lt;!&ndash;可以定义多个学生&ndash;&gt;
    <name>zzl</name>&lt;!&ndash;学生姓名&ndash;&gt;
    <sex>male</sex>&lt;!&ndash;学生性别（枚举）：male/female&ndash;&gt;
    <date>1999-01-06</date>&lt;!&ndash;出生日期&ndash;&gt;
    <course id="1010">
        <name>xml</name>
        <credit>2.0</credit>&lt;!&ndash;学分&ndash;&gt;
        <note>this is a very important class</note>
        &lt;!&ndash;课程分数，属性type表示成绩性质（枚举）：正常/补考/重修&ndash;&gt;
        <score type="normal">99.9</score>
    </course>&lt;!&ndash;一个学生可选修多门课程&ndash;&gt;
    <course id="1011">
        <name>java</name>
        <credit>3.0</credit>
        <note>java program design</note>
        <score type="normal">99.99</score>
    </course>
</student>
<student id="0121710870721">
    <name>lfb</name>
    <sex>female</sex>
    <date>1999-11-19</date>
    <course id="1010">
        <name>xml</name>
        <credit>2.0</credit>
        <note>this is a very important class</note>
        <score type="normal">98.88</score>
    </course>
</student>
<student id="0121710870721">
    <name>lfb</name>
    <sex>female</sex>
    <date>1999-11-19</date>
    <course id="1010">
        <name>xml</name>
        <credit>2.0</credit>
        <note>this is a very important class</note>
        <score type="normal">98.88</score>
    </course>
</student>
<student id="0121710870721">
    <name>lfb</name>
    <sex>female</sex>
    <date>1999-11-19</date>
    <course id="1010">
        <name>xml</name>
        <credit>2.0</credit>
        <note>this is a very important class</note>
        <score type="normal">98.88</score>
    </course>
</student>
<student id="0121710870721">
    <name>lfb</name>
    <sex>female</sex>
    <date>1999-11-19</date>
    <course id="1010">
        <name>xml</name>
        <credit>2.0</credit>
        <note>this is a very important class</note>
        <score type="normal">98.88</score>
    </course>
</student>
<student id="0121710870721">
    <name>lfb</name>
    <sex>female</sex>
    <date>1999-11-19</date>
    <course id="1010">
        <name>xml</name>
        <credit>2.0</credit>
        <note>this is a very important class</note>
        <score type="normal">98.88</score>
    </course>
</student>
</school>
-->
