=== zhouzilong168/javalearning/out/production/javalearning/xml/work2.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 rel. 2 U (http://www.xmlspy.com) by 123 (456) -->
<!ELEMENT quotedoc (quotelist, catalog)>
<!ELEMENT quotelist (quote+)>
<!ATTLIST quotelist
        author CDATA #REQUIRED
        quotes CDATA #REQUIRED
        >
<!ELEMENT quote (#PCDATA)>
<!ATTLIST quote
        source CDATA #IMPLIED
        author CDATA #IMPLIED
        >
<!ELEMENT catalog (amazon, elcorteingles)>
<!ATTLIST catalog
        items CDATA #REQUIRED
        >
<!ELEMENT amazon (product+)>
<!ATTLIST amazon
        items CDATA #REQUIRED
        >
<!ELEMENT elcorteingles (product)>
<!ATTLIST elcorteingles
        items CDATA #REQUIRED
        >
<!ELEMENT product (ranking?, (title | titulo)+, (asin | isbn)+, (author | autor)+, (image | imagen)+, small_image?, (list_price | precio)+, (release_date | fecha_de_publicaci贸n)+, (binding | Encuadernaci贸n)+, availability?, (tagged_url | librourl)+)>
<!ATTLIST product
        xml:lang CDATA #IMPLIED
        >
<!ELEMENT Encuadernaci贸n (#PCDATA)>
<!ELEMENT asin (#PCDATA)>
<!ELEMENT isbn (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT availability (#PCDATA)>
<!ELEMENT binding (#PCDATA)>
<!ELEMENT fecha_de_publicaci贸n (#PCDATA)>
<!ELEMENT image (#PCDATA)>
<!ELEMENT imagen (#PCDATA)>
<!ELEMENT librourl (#PCDATA)>
<!ELEMENT list_price (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT ranking (#PCDATA)>
<!ELEMENT release_date (#PCDATA)>
<!ELEMENT small_image (#PCDATA)>
<!ELEMENT tagged_url (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT titulo (#PCDATA)>

=== zhouzilong168/javalearning/src/xml/work2.xml
<?xml version="1.0" ?>
<!DOCTYPE quotedoc SYSTEM "work2.dtd">
<quotedoc>
    <quotelist author="鲁迅" quotes="文化大牛">
        <quote>近代社会的黑暗</quote>
        <quote>近代社会的白昼</quote>
    </quotelist>
    <catalog items="Java核心技术系列">
        <amazon items="compute">
            <product>
                <ranking>first</ranking>
                <title>Effective Java</title>
                <isbn>9780321356680</isbn>
                <author>Addison-Wesley</author>
                <image>blue</image>
                <small_image>white</small_image>
                <list_price>54.99$</list_price>
                <release_date>2008-05-28</release_date>
                <binding>Paperback</binding>
                <tagged_url>https:~subject/</tagged_url>
            </product>
        </amazon>
        <elcorteingles items="">
            <product>
                <ranking>first</ranking>
                <title>Effective Java</title>
                <isbn>9780321356680</isbn>
                <author>Addison-Wesley</author>
                <image>blue</image>
                <small_image>white</small_image>
                <list_price>54.99$</list_price>
                <release_date>2008-05-28</release_date>
                <binding>Paperback</binding>
                <tagged_url>https:~subject/</tagged_url>
            </product>
        </elcorteingles>
    </catalog>
</quotedoc>
